

export enum KalturaExternalMediaEntryOrderBy {
    createdAtAsc = '+createdAt',
	createdAtDesc = '-createdAt',
	durationAsc = '+duration',
	durationDesc = '-duration',
	endDateAsc = '+endDate',
	endDateDesc = '-endDate',
	lastPlayedAtAsc = '+lastPlayedAt',
	lastPlayedAtDesc = '-lastPlayedAt',
	mediaTypeAsc = '+mediaType',
	mediaTypeDesc = '-mediaType',
	moderationCountAsc = '+moderationCount',
	moderationCountDesc = '-moderationCount',
	nameAsc = '+name',
	nameDesc = '-name',
	partnerSortValueAsc = '+partnerSortValue',
	partnerSortValueDesc = '-partnerSortValue',
	playsAsc = '+plays',
	playsDesc = '-plays',
	rankAsc = '+rank',
	rankDesc = '-rank',
	recentAsc = '+recent',
	recentDesc = '-recent',
	startDateAsc = '+startDate',
	startDateDesc = '-startDate',
	totalRankAsc = '+totalRank',
	totalRankDesc = '-totalRank',
	updatedAtAsc = '+updatedAt',
	updatedAtDesc = '-updatedAt',
	viewsAsc = '+views',
	viewsDesc = '-views',
	weightAsc = '+weight',
	weightDesc = '-weight'
}