

export enum KalturaContainerFormat {
    applehttp = 'applehttp',
	avi = 'avi',
	bif = 'bif',
	bmp = 'bmp',
	copy = 'copy',
	flv = 'flv',
	hls = 'hls',
	isma = 'isma',
	ismv = 'ismv',
	jpg = 'jpg',
	m2ts = 'm2ts',
	m4v = 'm4v',
	mkv = 'mkv',
	mov = 'mov',
	mp3 = 'mp3',
	mp4 = 'mp4',
	mpeg = 'mpeg',
	mpegts = 'mpegts',
	mxf = 'mxf',
	ogg = 'ogg',
	ogv = 'ogv',
	pdf = 'pdf',
	png = 'png',
	swf = 'swf',
	wav = 'wav',
	webm = 'webm',
	wma = 'wma',
	wmv = 'wmv',
	wvm = 'wvm',
	_3gp = '3gp'
}