

export enum KalturaCatalogItemLanguage {
    ar = 'Arabic',
	cmn = 'Mandarin Chinese',
	cy = 'Welsh',
	da = 'Danish',
	de = 'German',
	el = 'Greek',
	en = 'English',
	enGb = 'English (British)',
	enUs = 'English (American)',
	es = 'Spanish',
	esXl = 'Spanish (Latin America)',
	fi = 'Finnish',
	fr = 'French',
	frCa = 'French (Canada)',
	ga = 'Irish',
	gd = 'Gaelic (Scottish)',
	he = 'Hebrew',
	hi = 'Hindi',
	hu = 'Hungarian',
	in = 'Indonesian',
	is = 'Icelandic',
	it = 'Italian',
	ja = 'Japanese',
	ko = 'Korean',
	ml = 'Malayalam',
	nl = 'Dutch',
	no = 'Norwegian',
	pl = 'Polish',
	pt = 'Portuguese',
	ptBr = 'Portuguese (Brazil)',
	ro = 'Romanian',
	ru = 'Russian',
	sv = 'Swedish',
	ta = 'Tamil',
	th = 'Thai',
	tr = 'Turkish',
	uk = 'Ukrainian',
	ur = 'Urdu',
	vi = 'Vietnamese',
	yue = 'Cantonese',
	zh = 'Chinese',
	zhTw = 'Taiwanese Mandarin',
	zu = 'Zulu'
}