

export enum KalturaCatalogItemLanguage {
    ar = 'Arabic',
	cmn = 'Mandarin Chinese',
	da = 'Danish',
	de = 'German',
	en = 'English',
	enGb = 'English (British)',
	enUs = 'English (American)',
	es = 'Spanish',
	fi = 'Finnish',
	fr = 'French',
	he = 'Hebrew',
	hi = 'Hindi',
	is = 'Icelandic',
	it = 'Italian',
	ja = 'Japanese',
	ko = 'Korean',
	nl = 'Dutch',
	no = 'Norwegian',
	pl = 'Polish',
	pt = 'Portuguese',
	ru = 'Russian',
	sv = 'Swedish',
	th = 'Thai',
	tr = 'Turkish',
	yue = 'Cantonese',
	zh = 'Chinese'
}