

export enum KalturaReportType {
    applications = '16',
	appDomainUniqueActiveUsers = '40',
	browsers = '23',
	browsersFamilies = '33',
	contentContributions = '7',
	contentDropoff = '2',
	contentInteractions = '3',
	entryUsage = '27',
	live = '24',
	mapOverlay = '4',
	mapOverlayCity = '30',
	mapOverlayCountry = '36',
	mapOverlayRegion = '37',
	operatingSystem = '22',
	operatingSystemFamilies = '32',
	partnerUsage = '201',
	platforms = '21',
	quiz = 'quiz.QUIZ',
	quizAggregateByQuestion = 'quiz.QUIZ_AGGREGATE_BY_QUESTION',
	quizUserAggregateByQuestion = 'quiz.QUIZ_USER_AGGREGATE_BY_QUESTION',
	quizUserPercentage = 'quiz.QUIZ_USER_PERCENTAGE',
	reachUsage = '28',
	specificUserEngagement = '12',
	specificUserUsage = '18',
	topContent = '1',
	topContentContributors = '39',
	topContentCreator = '38',
	topContributors = '5',
	topCreators = '20',
	topCustomVar1 = '29',
	topPlaybackContext = '25',
	topSources = '41',
	topSyndication = '6',
	uniqueUsersPlay = '35',
	userContentDropoff = '14',
	userContentInteractions = '15',
	userEngagement = '11',
	userEngagementTimeline = '34',
	userTopContent = '13',
	userUsage = '17',
	varUsage = '19',
	vpaasUsage = '26'
}