

export enum KalturaAuditTrailObjectType {
    accessControl = 'accessControl',
	batchJob = 'BatchJob',
	category = 'category',
	categoryEntry = 'categoryEntry',
	conversionProfile2 = 'conversionProfile2',
	emailIngestionProfile = 'EmailIngestionProfile',
	entry = 'entry',
	fileSync = 'FileSync',
	flavorAsset = 'flavorAsset',
	flavorParams = 'flavorParams',
	flavorParamsConversionProfile = 'flavorParamsConversionProfile',
	flavorParamsOutput = 'flavorParamsOutput',
	kshow = 'kshow',
	kshowKuser = 'KshowKuser',
	kuser = 'kuser',
	mediaInfo = 'mediaInfo',
	metadata = 'Metadata',
	metadataProfile = 'MetadataProfile',
	moderation = 'moderation',
	partner = 'Partner',
	permission = 'Permission',
	reachProfile = 'ReachProfile',
	roughcut = 'roughcutEntry',
	syndication = 'syndicationFeed',
	thumbnailAsset = 'thumbAsset',
	thumbnailParams = 'thumbParams',
	thumbnailParamsOutput = 'thumbParamsOutput',
	uiConf = 'uiConf',
	uploadToken = 'UploadToken',
	userLoginData = 'UserLoginData',
	userRole = 'UserRole',
	widget = 'widget'
}