

export enum KalturaESearchLanguage {
    arabic = 'Arabic',
	basque = 'Basque',
	brazilian = 'Brazilian',
	bulgarian = 'Bulgarian',
	catalan = 'Catalan',
	chinese = 'Chinese',
	czech = 'Czech',
	danish = 'Danish',
	dutch = 'Dutch',
	english = 'English',
	finnish = 'Finnish',
	french = 'French',
	galician = 'Galician',
	german = 'German',
	greek = 'Greek',
	hindi = 'Hindi',
	hungrian = 'Hungarian',
	indonesian = 'Indonesian',
	italian = 'Italian',
	japanese = 'Japanese',
	korean = 'Korean',
	latvian = 'Latvian',
	lithuanian = 'Lithuanian',
	norwegian = 'Norwegian',
	persian = 'Persian',
	portuguese = 'Prtuguese',
	romanian = 'Romanian',
	russian = 'Russian',
	sorani = 'Sorani',
	spanish = 'Spanish',
	swedish = 'Swedish',
	thai = 'Thai',
	turkish = 'Turkish'
}