

export enum KalturaMailType {
    mailTypeAccountReactiveConfirm = '86',
	mailTypeAccountUpgradeConfirm = '80',
	mailTypeAddedKalturaToHisFavorites = '32',
	mailTypeAddedKalturaToHisFavoritesSubscribed = '42',
	mailTypeAddedKalturaToYourFavorites = '23',
	mailTypeAddedToClipFavorites = '12',
	mailTypeAddedToFavorites = '11',
	mailTypeBulkuploadAborted = '66',
	mailTypeBulkuploadFailed = '65',
	mailTypeBulkuploadFinished = '64',
	mailTypeBulkDownloadReady = '63',
	mailTypeClipAdded = '30',
	mailTypeClipAddedYourKaltura = '20',
	mailTypeClipContributed = '40',
	mailTypeKalturaNewsletter = '10',
	mailTypeLiveReportExportAbort = '132',
	mailTypeLiveReportExportFailure = '131',
	mailTypeLiveReportExportSuccess = '130',
	mailTypeLoginMailReset = '52',
	mailTypeNewCommentInKaltura = '24',
	mailTypeNewCommentInKalturaYouContributed = '33',
	mailTypeNewCommentInKalturaYouSubscribed = '43',
	mailTypeNewCommentInProfile = '13',
	mailTypeNotifyErr = '70',
	mailTypeObjectsCsv = '135',
	mailTypePasswordReset = '51',
	mailTypeRegisterConfirm = '50',
	mailTypeRegisterConfirmVideoService = '54',
	mailTypeRoughcutCreated = '22',
	mailTypeRoughcutCreatedSubscribed = '41',
	mailTypeSystemUserCredentialsSaved = '113',
	mailTypeSystemUserNewPassword = '112',
	mailTypeSystemUserResetPassword = '110',
	mailTypeSystemUserResetPasswordSuccess = '111',
	mailTypeUsersCsv = '133',
	mailTypeVideoAdded = '21',
	mailTypeVideoCreated = '31',
	mailTypeVideoIsReady = '62',
	mailTypeVideoReady = '60',
	mailTypeVideoServiceNotice = '81',
	mailTypeVideoServiceNoticeAccountDeleted = '84',
	mailTypeVideoServiceNoticeAccountLocked = '83',
	mailTypeVideoServiceNoticeLimitReached = '82',
	mailTypeVideoServiceNoticeUpgradeOffer = '85'
}