

export enum KalturaESearchCategoryFieldName {
    contributionPolicy = 'contribution_policy',
	createdAt = 'created_at',
	depth = 'depth',
	description = 'description',
	directEntriesCount = 'direct_entries_count',
	directSubCategoriesCount = 'direct_sub_categories_count',
	displayInSearch = 'display_in_search',
	entriesCount = 'entries_count',
	fullIds = 'full_ids',
	fullName = 'full_name',
	inheritanceType = 'inheritance_type',
	inheritedParentId = 'inherited_parent_id',
	membersCount = 'members_count',
	moderation = 'moderation',
	_name = 'name',
	parentId = 'parent_id',
	pendingEntriesCount = 'pending_entries_count',
	pendingMembersCount = 'pending_members_count',
	privacy = 'privacy',
	privacyContext = 'privacy_context',
	privacyContexts = 'privacy_contexts',
	referenceId = 'reference_id',
	tags = 'tags',
	updatedAt = 'updated_at',
	userId = 'user_id',
	userIds = 'user_ids'
}