

export enum KalturaESearchEntryFieldName {
    accessControlId = 'access_control_id',
	adminTags = 'admin_tags',
	conversionProfileId = 'conversion_profile_id',
	createdAt = 'created_at',
	creatorId = 'creator_kuser_id',
	credit = 'credit',
	description = 'description',
	endDate = 'end_date',
	entitledUserEdit = 'entitled_kusers_edit',
	entitledUserPublish = 'entitled_kusers_publish',
	entryType = 'entry_type',
	externalSourceType = 'external_source_type',
	id = 'id',
	isLive = 'is_live',
	isQuiz = 'is_quiz',
	lengthInMsecs = 'length_in_msecs',
	mediaType = 'media_type',
	moderationStatus = 'moderation_status',
	_name = 'name',
	parentEntryId = 'parent_id',
	pushPublish = 'push_publish',
	recordedEntryId = 'recorded_entry_id',
	redirectEntryId = 'redirect_entry_id',
	referenceId = 'reference_id',
	rootId = 'root_id',
	siteUrl = 'site_url',
	sourceType = 'source_type',
	startDate = 'start_date',
	tags = 'tags',
	templateEntryId = 'template_entry_id',
	updatedAt = 'updated_at',
	userId = 'kuser_id',
	userNames = 'user_names'
}